### ISSUE TITLE
Quit option in file menu doesn't end the process...

### ISSUE THREAD

**Issue by HugoMartel** [HugoMartel/Projet_ThL#1]
# Clicking the quit option closes the window but doesn't quit the command

Maybe not calling the destroy function ?

*PopOs! x86_64 Kernel 5.15.5*

**Comment by TT-txt** [comment]
Fixed in [697c5e1](https://github.com/HugoMartel/Projet_ThL/commit/697c5e11326b81f0e64641104417e776d12e7978)
