### ISSUE TITLE
Enable keymap detection

### ISSUE THREAD

**Issue by HugoMartel** [HugoMartel/Projet_ThL#2]
## Ctrl+A and Ctrl+Z are working but with the QWERTY layout....

*PopOS! x86_64 Kernel: 5.15.5*

**Comment by TT-txt** [comment]
same issue as [imgui 2959](https://github.com/ocornut/imgui/issues/2959), maybe fixed with this [gist](https://gist.github.com/blep/59b5a69b9671f0a90f3576d14520eb5c)

**Comment by TT-txt** [comment]
Workarround fix in [048a2ee](https://github.com/HugoMartel/Projet_ThL/commit/048a2eeaf644b56fbb19c53fe84d0bf166e661b7), real fix could be implemented somewhere in [imgui_widgets.cpp](https://github.com/HugoMartel/Projet_ThL/blob/main/lib/imgui/imgui_widgets.cpp), at line numbers:
- undo at line [4292](https://github.com/HugoMartel/Projet_ThL/blob/main/lib/imgui/imgui_widgets.cpp#L4292)
- redo at line [4293](https://github.com/HugoMartel/Projet_ThL/blob/main/lib/imgui/imgui_widgets.cpp#L4293)
- select all at line [4348](https://github.com/HugoMartel/Projet_ThL/blob/main/lib/imgui/imgui_widgets.cpp#L4348)
